AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS Resources"

Resources:
  WorkflowJob:
    Type: AWS::Glue::Workflow
    Properties:
      Description: Create workflow
      MaxConcurrentRuns: 1
      Name: jobworkflow

  GlueJobImport:
    Type: AWS::Glue::Job
    Properties:
      Name: Sales_Glue_via_CFT
      Description: Ingests data from s3 and writes it as a parquet file to the data lake
      ExecutionClass: FLEX
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 6
      Role: arn:aws:iam::278557494232:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://finalprojectinput/github/sales/Sales.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"

    
  WorkflowStartTrigger:    
    Type: AWS::Glue::Trigger
    Properties:
      Actions: 
        - JobName: !Ref GlueJobImport
      WorkflowName: !Ref WorkflowJob
      Description: Run Bitcch Run
      Name: Triggering the Glue Job
      Schedule: String
      StartOnCreation: True
      Type: ON_DEMAND
      WorkflowName: String
      
