AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS Resources"

Resources:
  WorkflowJob:
    Type: AWS::Glue::Workflow
    Properties:
      Description: Create workflow
      MaxConcurrentRuns: 1
      Name: jobworkflow

  GlueJobImport:
    Type: AWS::Glue::Job
    Properties:
      Name: data-ingestion
      Description: Ingests data from s3 and writes it as a parquet file to the data lake
      ExecutionClass: FLEX
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 6
      Role: arn:aws:iam::278557494232:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://finalprojectinput/github/products/Products_Glue_Job.py
      BookmarkOptions:
        JobBookmarkRunId: true

  WorkflowStartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: StartTrigger
      Type: ON_DEMAND
      Description: Trigger for starting the workflow
      Actions:
        - JobName: !Ref GlueJobImport
      WorkflowName: !Ref WorkflowJob
