AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS Resources and run Glue job"

Resources:
  WorkflowJob:
    Type: AWS::Glue::Workflow
    Properties:
      Description: "Create workflow"
      MaxConcurrentRuns: 1
      Name: jobworkflow

  GlueJobImport:
    Type: AWS::Glue::Job
    Properties:
      Name: data-ingestion1
      Description: "Ingests data from S3 and writes it as a parquet file to the data lake"
      ExecutionClass: FLEX
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 6
      Role: arn:aws:iam::278557494232:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://finalprojectinput/github/products/Products_Glue_Job.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"

  MyScheduledTrigger:
  Type: 'AWS::Glue::Trigger'
  Properties:
    Name: MyScheduledTrigger
    Type: SCHEDULED
    Schedule: 'cron(15 14 15 2 ? 2024)'  # This runs the job on February 15, 2024 at 14:15 UTC
    Actions:
      - JobName: !Ref GlueJobImport
    WorkflowName: !Ref WorkflowJob


