AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS Resources and run Glue job"

Resources:
  WorkflowJob:
    Type: AWS::Glue::Workflow
    Properties:
      Description: "Create workflow"
      MaxConcurrentRuns: 1
      Name: jobworkflow

  GlueJobImport:
    Type: AWS::Glue::Job
    Properties:
      Name: data-ingestion1
      Description: "Ingests data from S3 and writes it as a parquet file to the data lake"
      ExecutionClass: FLEX
      GlueVersion: 4.0
      MaxRetries: 0
      NumberOfWorkers: 6
      Role: arn:aws:iam::278557494232:role/LabRole
      Timeout: 90
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://finalprojectinput/github/products/Products_Glue_Job.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"

  WorkflowStartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: StartTrigger
      Type: ON_DEMAND  # Or adjust for desired triggering (SCHEDULED, EVENT, etc.)
      Description: "Trigger for starting the workflow"
      Actions:
        - JobName: !Ref GlueJobImport
      WorkflowName: !Ref WorkflowJob

Outputs:
  JobRunId:
    Description: Job Run ID of the triggered Glue job
    Value: !GetAtt GlueJobImport.JobRuns[0].Id
